---
name: tanager
description: An obscure red bird.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - avengemedia/danklinux 
    install:
      packages:
        - btop
        - eog
        - gnome-calculator
        - gnome-clocks
        - gnome-text-editor
        - gparted
        - qemu
        - libvirt
        - papers
        - screen
        - tailscale
        - telnet
        - virt-manager
        - noctalia-shell
        - swayidle
        - brightnessctl
        - ImageMagick
        - ddcutil
        - cliphist
        - cava
        - wlsunset
        - niri
        - fastfetch

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - gnome-software
        - gnome-system-monitor

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - ca.desrt.dconf-editor
          - com.brave.Browser
          - com.mattjakeman.ExtensionManager
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - org.atheme.audacious
          - org.fedoraproject.MediaWriter
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.mozilla.firefox
          - org.remmina.Remmina
          - org.videolan.VLC
          - page.codeberg.libre_menu_editor.LibreMenuEditor
          - page.tesk.Refine

  - type: signing

  - type: systemd
    system:
      enabled:
        - tailscaled
        - libvirtd
        - sshd

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '3d'

  - type: gnome-extensions
    install:
      - 6670 #Bluetooth Battery Meter
      - 3193 #Blur my Shell
      - 615  #AppIndicator and KStatusNotifierItem Support
      - 517  #Caffeine
      - 744  #Hide Activities Button
      - 4099 #No overview at start-up
      - 5964 #Quick Settings Audio Devices Hider
      - 19   #User Themes

  - type: kargs
    kargs:
      - split_lock_detect=off
