---
name: tanager
description: An obscure red bird.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      copr:
        - avengemedia/danklinux 
        - sneexy/zen-browser
        - lizardbyte/beta
    install:
      packages:
        - brightnessctl
        - btop
        - cava
        - chezmoi
        - cliphist
        - ddcutil
        - eog
        - fastfetch
        - fira-code-fonts
        - gamescope
        - gnome-calculator
        - gnome-clocks
        - gnome-text-editor
        - gparted
        - ImageMagick
        - kitty
        - libvirt
        - mangohud
        - mediawriter
        - mpv
        - mpv-devel
        - niri
        - noctalia-shell
        - papers
        - python3-pip
        - qemu
        - qt6ct
        - screen
        - steam
        - sunshine
        - swayidle
        - tailscale
        - telnet
        - virt-manager
        - wlsunset
        - xfce-polkit
        - yazi
        - zed
        - zen-browser

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - gnome-software
        - gnome-system-monitor

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - com.ranfdev.DistroShelf
          - io.github.flattool.Ignition
          - io.github.kolunmi.Bazaar
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - org.remmina.Remmina
          - page.codeberg.libre_menu_editor.LibreMenuEditor

  - type: signing

  - type: systemd
    system:
      enabled:
        - tailscaled
        - libvirtd
        - sshd

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: '3d'

  - type: gnome-extensions
    install:
      - 6670 #Bluetooth Battery Meter
      - 3193 #Blur my Shell
      - 615  #AppIndicator and KStatusNotifierItem Support
      - 517  #Caffeine
      - 744  #Hide Activities Button
      - 4099 #No overview at start-up
      - 5964 #Quick Settings Audio Devices Hider

  - type: kargs
    kargs:
      - split_lock_detect=off
